# Site settings
encoding: utf-8
title: Cody
description: zzc的个人博客
baseurl: "https://ERcun.GitHub.io" 
# baseurl: ''
github_username:  cody1991
paginate: 8
paginate_path: "/page:num"
footer_twitter: "Twitter"
footer_twitter_site: "https://twitter.com/cody19910828"
footer_github: "GitHub"
footer_resume: "简历"
footer_resume_site: "https://ERcun.GitHub.io/aboutme/index.html"
port: 8070
gems: [jekyll-paginate]
